### ISSUE TITLE
Laravel integration 

### ISSUE THREAD

**Issue by Jijiri89** [patricpoba/arkesel-php#1]
Please, I was going through your documentation of laravel integration of arkersel sms gateway. My problem is that, after installing your package through composer, where can I locate the facade(patricpoba/Arkaseel/SMS) in my project?

**Comment by patricpoba** [comment]
@Jijiri89  kindly take a look at the examples in the usage section. The namespaces are indicated of the location of files in the `/vendor/patricpoba/arkesel-php`  folder.

**Comment by patricpoba** [comment]
@Jijiri89 kindly take a look at the examples in the usage section. The namespaces are indicated of the location of files in the `/vendor/patricpoba/arkesel-php` folder.
